import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    absolute: 'RollerTools'
  },
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className + ' min-h-screen bg-gray-900'}>
        <header className='flex justify-center p-5 shadow-lg bg-slate-800'>
          <nav>
            <Link href={'/profit-calculator'}>Profit calculator</Link>
          </nav>
        </header>
        <main className='p-5 flex flex-col items-center'>
          {children}
        </main>
      </body>
    </html>
  )
}
